### ISSUE TITLE
Template path not found

### ISSUE THREAD

**Issue by rbramley** [gofair-foundation/qualification-issue-creation-action#47]
Run gofair-foundation/qualification-issue-creation-action@v0.8
Error: ENOENT: no such file or directory, open '/home/runner/work/fsr_qualification/fsr_qualification/.github/ISSUE_TEMPLATE/fsr-qualification.md'

**Comment by rbramley** [comment]
Think it needs to use https://github.com/actions/checkout with e.g.
``` 
- uses: actions/checkout@v4
  with:
    sparse-checkout: |
      .github
```
